[phases.setup]
nixPkgs = ['python311', 'gcc', 'pipenv']

[phases.install]
cmds = [
  'python3 -m venv /opt/venv',
  '. /opt/venv/bin/activate',
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.start]
cmd = 'streamlit run st_lit.py --server.port 8080 --server.address 0.0.0.0'